### ISSUE TITLE
TWW Pre-Patch bug

### ISSUE THREAD

**Issue by Spennig** [rursache/InFlight-TWW#3] opened 2024-07-25 00:53 UTC
Got this when logging in on Pre-patch, otherwise addon seems to be working as it did before.

1x InFlight_Load/InFlight_Load.lua:129: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@InFlight_Load/InFlight_Load.lua"]:129: in function `SetupInFlight'
[string "@InFlight_Load/InFlight_Load.lua"]:21: in function `?'
[string "@InFlight_Load/InFlight_Load.lua"]:3: in function <InFlight_Load/InFlight_Load.lua:3>

Locals:
self = InFlight {
 L = <table> {
 }
}
panel = Frame {
 name = "InFlight"
}
(*temporary) = nil
(*temporary) = Frame {
 name = "InFlight"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
InFlight = InFlight {
 L = <table> {
 }
}

**Comment by rursache** [comment] 2024-07-25 08:02
duplicate of https://github.com/rursache/InFlight-WW/issues/2

**Closed as completed by rursache** 2024-07-25 08:02 UTC
