### ISSUE TITLE
Error message when changing colors

### ISSUE THREAD

**Issue by Ahornblatt-natur** [rursache/InFlight-TWW#24] opened 2024-10-27 15:37 UTC
Hello, I just wanted to change the background during the flight and then this error message came up:

13x InFlight/InFlight.lua:913: attempt to index global 'OpacitySliderFrame' (a nil value)
[string "@InFlight/InFlight.lua"]:913: in function <InFlight/InFlight.lua:902>
[string "@ElvUI/Mainline/Modules/Blizzard/ColorPicker.lua"]:109: in function <...dOns/ElvUI/Mainline/Modules/Blizzard/ColorPicker.lua:107>

Locals:
a1 = nil
dbc = <table> {
 a = 0.750000
 b = 0.168627
 g = 0.168627
 r = 0.168627
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0.168627
(*temporary) = 0.168627
(*temporary) = 0.168627
(*temporary) = "attempt to index global 'OpacitySliderFrame' (a nil value)"
db = <table> {
 outline = true
 backcolor = <table> {
 }
 barcolor = <table> {
 }
 border = "None"
 fontsize = 14
 countup = false
 rp = "TOP"
 twolines = false
 fontcolor = <table> {
 }
 texture = "Melli Dark"
 chatlog = true
 p = "TOP"
 spark = false
 confirmflight = false
 perchar = false
 bordercolor = <table> {
 }
 outlinetime = true
 inline = true
 y = -117
 x = -2
 unknowncolor = <table> {
 }
 fill = false
 height = 25
 font = "Poppins-Medium"
 totext = " --> "
 width = 420
}
InFlight = InFlight {
 defaults = <table> {
 }
 db = <table> {
 }
 L = <table> {
 }
 debug = false
}

**Comment by rursache** [comment] 2024-10-27 15:38
duplicate of https://github.com/rursache/InFlight-TWW/issues/20

**Closed as completed by rursache** 2024-10-27 15:38 UTC

**Comment by Ahornblatt-natur** [comment] 2024-10-28 07:51
Oh, I'm sorry if I posted it twice. Is there a solution? I haven't found anything about it in other posts?!

**Comment by superwario15** [comment] 2024-10-28 07:56
No, you didn't, he just marked this ticket as the same error that has been seen before.

This error was rectified with an earlier fix I made a few months ago. @mapleleaf202324 are you using the latest version of this addon from this Github repository?

**Comment by superwario15** [comment] 2024-10-28 07:58
@rursache The version of this addon on Curseforge appears to be out of date (11.0.6), which wouldn't contain this fix. Could you push the latest version to Curseforge?

**Comment by rursache** [comment] 2024-10-28 09:23
@superwario15 indeed, a mistake on my part!
v11.0.7 of the addon was submitted to curseforge. the updated version have the fix for this issue

@mapleleaf202324 please look out for this version!
